### ISSUE TITLE
Events dates are stored in varchar field in DB

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-sql-provider#9]
The column "eve_date" from rdap.event table (a table that contains the information about events that have occurred on an instance of an object class) is defined as VARCHAR(45). However, if an user fill this field with a random string that doesn't fit with any date format, and the server execute a query, the following error is displayed in server's logs:

10-Oct-2017 15:53:58.786 SEVERE [http-nio-8080-exec-2] mx.nic.rdap.server.servlet.RdapServlet.doGet java.sql.SQLException: Bad format for Timestamp 'PATATA PATATA 2016-11-13 00:09:20' in column 4.
 mx.nic.rdap.db.exception.RdapDataAccessException: java.sql.SQLException: Bad format for Timestamp 'PATATA PATATA 2016-11-13 00:09:20' in column 4.
	at mx.nic.rdap.sql.impl.DomainDAOImpl.searchByName(DomainDAOImpl.java:70)
	at mx.nic.rdap.server.servlet.DomainSearchServlet.getPartialSearch(DomainSearchServlet.java:96)
	at mx.nic.rdap.server.servlet.DomainSearchServlet.doRdapDaGet(DomainSearchServlet.java:67)
	at mx.nic.rdap.server.servlet.DomainSearchServlet.doRdapDaGet(DomainSearchServlet.java:22)
	at mx.nic.rdap.server.servlet.DataAccessServlet.doRdapGet(DataAccessServlet.java:38)
	at mx.nic.rdap.server.servlet.RdapServlet.doGet(RdapServlet.java:34)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
...
Caused by: java.sql.SQLException: Bad format for Timestamp 'PATATA PATATA 2016-11-13 00:09:20' in column 4.
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1157)
	at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:130)
	at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:5946)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:5616)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:5645)
mainDAOImpl.searchByName(DomainDAOImpl.java:65)...
	... 31 more

It is necessary to treat the eve_date as a date, in order to avoid any issue when parsing the string to a date format.

**Comment by pcarana** [comment]
Dates of events are now stored as DATETIME, the code was already prepared to load this kind of values, only the DB was inconsistent.

**Comment by TheRedTrainer** [comment]
Verified. The events dates are treated as date-time data, not as varchar as they were treated before.
